Repository Arc-Computer/arc-cli, pull requests merged in 2025-06, with the labels that each got.

#1 Updated Arc-Eval Database Architecture for TimescaleDB Cloud Integration
  docs/db/DATABASE.md
Labels: documentation

#14 created github_issue_timescale.md contains issues to work on.
  github_issues_timescaledb.md
Labels: documentation

#31 feat: Demo Agent Configurations (Issue #6)
  arc/cli_validate.py
  arc/ingestion/__init__.py
  arc/ingestion/normalizer.py
  arc/ingestion/parser.py
  arc/tests/unit/test_ingestion.py
  examples/configs/README.md
  examples/configs/audit_agent.yaml
  examples/configs/finance_agent_v1.yaml
  examples/configs/finance_agent_v2.yaml
  examples/configs/minimal_agent.yaml
  pyproject.toml
Labels: documentation, enhancement

#36 Implement TimescaleDB Architecture with Production-Ready Database Client
  arc/database/client.py
  arc/database/deploy_schema.py
  arc/tests/integration/test_database.py
  arc/tests/unit/__init__.py
  arc/tests/unit/test_database_client.py
  docs/db/TIMESCALEDB_ARCHITECTURE.md
Labels: enhancement

#33 feat: Developer-First CLI with Scenario Generation (Issue #4)
  arc/cli.py
  arc/cli/__init__.py
  arc/cli/__main__.py
  arc/cli/commands/__init__.py
  arc/cli/commands/analyze.py
  arc/cli/commands/diff.py
  arc/cli/commands/recommend.py
  arc/cli/commands/run.py
  arc/cli/commands/status.py
  arc/cli/commands/validate.py
  arc/cli/utils/__init__.py
  arc/cli/utils/console.py
  arc/cli/utils/state.py
  arc/cli_main.py
  arc/core/models/scenario.py
  arc/sandbox/scenarios/generator.py
  arc/sandbox/scenarios/quality_scorer.py
  arc/scenarios/assumption_extractor.py
  arc/scenarios/deduplicator.py
  arc/scenarios/failure_patterns/__init__.py
  arc/scenarios/failure_patterns/library.py
  arc/scenarios/failure_patterns/patterns/calculation/precision_loss.json
  arc/scenarios/failure_patterns/patterns/data/malformed_response.json
  arc/scenarios/failure_patterns/patterns/infrastructure/timeout_api_delay.json
  arc/scenarios/failure_patterns/patterns/logic/ambiguous_request.json
  arc/scenarios/generation_coordinator.py
  arc/scenarios/generator.py
  arc/scenarios/pattern_adapter.py
  arc/scenarios/pattern_selector.py
  arc/scenarios/quality_scorer.py
  arc/scenarios/scenario_instantiator.py
Labels: enhancement

#39 Fix simulation DB call
  arc/cli/utils/hybrid_state.py
  arc/database/client.py
Labels: codex

#42 Implement Core Database API for Modal Sandbox Integration
  arc/database/api.py
  arc/database/client.py
  arc/database/deploy_schema.py
  arc/database/schema/indexes.sql
  arc/database/schema/tables.sql
  arc/examples/sandbox_db_integration.py
  arc/sandbox/engine/simulator.py
  arc/sandbox/engine/trajectory_capture.py
  arc/sandbox/evaluation/reliability_scorer.py
  arc/tests/integration/test_database.py
  arc/tests/unit/__init__.py
  arc/tests/unit/test_database_api.py
  docs/db/SANDBOX_INTEGRATION_GUIDE.md
  docs/db/TIMESCALEDB_ARCHITECTURE.md
Labels: enhancement

#43 Fix QA failures and improve system robustness
  arc/cli/commands/analyze.py
  arc/cli/commands/diff.py
  arc/cli/commands/status.py
  arc/cli/utils/hybrid_state.py
  arc/cli/utils/state.py
  arc/database/api.py
  arc/database/client.py
  arc/tests/integration/test_database.py
  arc/tests/unit/test_database_client.py
  docs/db/DATABASE.md
  docs/db/TRAJECTORY_REQUIREMENTS.md
Labels: bug

#45 feat: Add comprehensive end-to-end pipeline test with database integr…
  arc/database/api.py
  arc/database/client.py
  arc/sandbox/engine/simulator.py
  arc/tests/e2e/database_inspection.py
  arc/tests/e2e/test_complete_pipeline.py
  arc/tests/integration/test_database.py
  docs/TESTING_GUIDE.md
Labels: bug

#50 fix: resolve critical file lock timeout issue
  arc/cli/commands/diff.py
  arc/cli/commands/run.py
  arc/cli/design_standards.py
  arc/cli/loading_interface.py
  arc/cli/utils/__init__.py
  arc/cli/utils/file_utils.py
  arc/cli/utils/hybrid_state.py
  arc/cli/utils/modal_auth.py
  arc/cli/utils/state.py
  arc/database/client.py
  arc/ingestion/parser.py
  arc/sandbox/engine/simulator.py
  arc/sandbox/engine/tool_behavior_engine.py
Labels: bug, enhancement

#55 QA Review Fixes: UUID Serialization and Modal Authentication
  arc/cli/commands/run.py
  arc/cli/commands/status.py
  arc/cli/utils/modal_auth.py
  arc/database/api.py
  arc/database/client.py
  arc/database/utils.py
  arc/sandbox/engine/simulator.py
  arc/tests/integration/test_database.py
Labels: bug

#60 feat: Add real-time execution monitoring and cost tracking
  arc/cli/commands/run.py
  arc/cli/loading_interface.py
Labels: claude

#65 Batch Processing System for Arc CLI
  README.md
  arc/cli/commands/run.py
  arc/cli/utils/json_utils.py
  arc/cli/utils/state.py
  arc/database/api.py
  arc/database/batch_processor.py
  arc/modal/public_api.py
  arc/sandbox/engine/simulator.py
  arc/simulation/modal_orchestrator.py
  public/arc-banner-readme.png
Labels: enhancement

#67 fix: Resolve Modal integration and reliability score issues - Modal i…
  arc/cli/commands/run.py
  arc/database/api.py
  arc/database/utils.py
  arc/modal/public_api.py
  arc/sandbox/engine/simulator.py
  arc/simulation/modal_orchestrator.py
Labels: bug, enhancement
